# Generated by Django 4.1.3 on 2022-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, max_length=50)),
                ('friend_id', models.IntegerField(default=0, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
