# Generated by Django 4.1.3 on 2022-12-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0002_rename_friend_id_friends_fid_alter_friends_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='fid',
            new_name='friend_id',
        ),
    ]
