# Generated by Django 4.1.3 on 2022-12-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0005_alter_friends_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
